name: Update RSS Feed

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual run

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3
    
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: "3.x"

      # Step 3: Run the RSS Feed Script
      - name: Run RSS Feed Script
        run: |
          python generate_rss.py
          
          # Git configuration for the bot account
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage changes and commit if any
          git add daily_feed.xml
          git commit -m "Update daily RSS feed" || echo "No changes to commit"
          
          # Push changes using the GitHub token for authentication
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
